server:
  port: 5001
spring:
  application:
    name: fastjee-config
  profiles:
    active: dev
  # 配置中心git仓库
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/murphyfei/Fastjee.git
          searchPaths: fastjee-config-repo
          username: 1083458319@qq.com
          password: Love5295201314

# 将配置中心注册到eureka实现高可用
eureka:
  instance:
    hostname: fastjee-config.com
  client:
    serviceUrl:
      defaultZone: http://fastjee:123456@fastjee-registration.com:5000/eureka/

logging:
  config: classpath:logback.xml